name: Pull Request When Closed.

on: 
  pull_request:
    types: [closed, assigned]

jobs:
  job-trigger-when-pr-closed:
    runs-on: ubuntu-latest
    steps:
    - name: Closing first message.
      run: | 
        echo "Hey!"
        echo "You have closed the pull request."
        echo "It should be working."