name: Actions Workflow

on: [push]

jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a

      - name: Printing enviroment variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: Cloning our repository
        id: clonerepo
        uses: actions/checkout@v1

      - name: List files Again Dude
        run: |
          pwd
          ls -a

      - name: Javascript action.
        id: jsaction
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Jorge
      
      - name: Log Greetoing Time
        run: echo "${{ steps.jsaction.outputs.time }}"

